# Generated by Django 2.1.1 on 2020-06-10 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('country_code', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'country_info',
            },
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crickinfo.Base')),
            ],
            options={
                'db_table': 'match_info',
            },
            bases=('crickinfo.base',),
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crickinfo.Base')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='PlayerImages/')),
                ('jersey_number', models.CharField(max_length=3)),
                ('total_matches', models.IntegerField(default=0)),
                ('runs', models.IntegerField(default=10)),
                ('highest_scores', models.IntegerField(default=0)),
                ('fifties', models.IntegerField(default=0)),
                ('hundreds', models.IntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crickinfo.Countries')),
            ],
            options={
                'db_table': 'player_info',
            },
            bases=('crickinfo.base',),
        ),
        migrations.CreateModel(
            name='PointsTable',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crickinfo.Base')),
                ('match', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('lose', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'points_table',
            },
            bases=('crickinfo.base',),
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crickinfo.Base')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('team_code', models.CharField(max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='TeamLogo/')),
                ('clubstate', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'team_info',
            },
            bases=('crickinfo.base',),
        ),
        migrations.AlterUniqueTogether(
            name='teams',
            unique_together={('name', 'team_code')},
        ),
        migrations.AddField(
            model_name='pointstable',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crickinfo.Teams'),
        ),
        migrations.AddField(
            model_name='players',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crickinfo.Teams'),
        ),
        migrations.AddField(
            model_name='matches',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='crickinfo.Teams'),
        ),
        migrations.AddField(
            model_name='matches',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='crickinfo.Teams'),
        ),
        migrations.AddField(
            model_name='matches',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='crickinfo.Teams'),
        ),
    ]
